CREATE TABLE Sensor (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar NOT NULL UNIQUE CHECK (LENGTH(name) >= 3 AND LENGTH(name) <= 30),
                        created_at timestamp
);

CREATE TABLE Measurement (
                             id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             temperature DOUBLE PRECISION NOT NULL CHECK (temperature >= -100 AND temperature <= 100),
                             raining boolean NOT NULL,
                             measured_at timestamp,
                             sensor_id int REFERENCES Sensor(id) ON DELETE CASCADE
);
